language: php
php:
  - '5.5'
  - '5.6'
env:
  - DB=mongodb
services:
  - mongodb
before_script:
  - sleep 15
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: php mageekguy.atoum.phar